# Generated by Django 2.0.8 on 2018-10-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181009_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSecondPage',
            fields=[
                ('subarticlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.SubArticlePage')),
            ],
            options={
                'verbose_name': '新闻二级页面',
            },
            bases=('home.subarticlepage',),
        ),
        migrations.CreateModel(
            name='ProductSecondPage',
            fields=[
                ('subarticlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.SubArticlePage')),
            ],
            options={
                'verbose_name': '产品二级页面',
            },
            bases=('home.subarticlepage',),
        ),
    ]
