# Generated by Django 2.0.8 on 2018-10-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newssecondpage_productsecondpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarticlepage',
            name='author',
            field=models.CharField(blank=True, max_length=32, verbose_name='作者'),
        ),
    ]
