# Generated by Django 2.0.8 on 2018-10-12 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181012_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkindpage',
            name='date',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
    ]
