# Generated by Django 2.0.8 on 2018-10-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0007_auto_20181012_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkindpage',
            name='navmenuitem_ptr',
        ),
        migrations.DeleteModel(
            name='ProductKindPage',
        ),
    ]
