# Generated by Django 2.0.8 on 2018-10-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0009_auto_20181014_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarticlepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='请按要求上传规定尺寸的图片，如尺寸不一样，请务必保持比例一致', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='缩略图'),
        ),
    ]
