# Generated by Django 2.0.8 on 2018-10-15 17:17

from django.db import migrations
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_subarticlepage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarticlepage',
            name='body',
            field=wagtail.core.fields.StreamField([('h2', wagtail.core.blocks.CharBlock(classname='title', icon='title', label='2号标题')), ('h3', wagtail.core.blocks.CharBlock(classname='title', icon='title', label='3号标题')), ('h4', wagtail.core.blocks.CharBlock(classname='title', icon='title', label='4号标题')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='段落')), ('aligned_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.TextBlock(required=True)), ('alignment', home.models.ImageFormatChoiceBlock())], icon='image', label='图片'))]),
        ),
    ]
