# Generated by Django 2.0.8 on 2018-10-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_caseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutitem',
            name='note_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注释说明（英文）'),
        ),
        migrations.AddField(
            model_name='caseitem',
            name='note_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注释说明（英文）'),
        ),
        migrations.AddField(
            model_name='salebranditem',
            name='note_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注释说明（英文）'),
        ),
        migrations.AddField(
            model_name='salehonoritem',
            name='note_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注释说明（英文）'),
        ),
        migrations.AlterField(
            model_name='aboutitem',
            name='note',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注释说明（中文）'),
        ),
        migrations.AlterField(
            model_name='caseitem',
            name='note',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注释说明（中文）'),
        ),
        migrations.AlterField(
            model_name='salebranditem',
            name='note',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注释说明（中文）'),
        ),
        migrations.AlterField(
            model_name='salehonoritem',
            name='note',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注释说明（中文）'),
        ),
    ]
