# Generated by Django 2.0.8 on 2018-10-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20181026_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='网站名称'),
        ),
        migrations.AddField(
            model_name='website',
            name='url',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='URL'),
        ),
    ]
